/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Comrade1280 (https://sketchfab.com/comrade1280)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/space-fighter-e766136d4871441289d37d44a4bbcd3b
title: Space Fighter
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  // const { nodes, materials } = useGLTF("/scene.gltf");
  const { nodes, materials } = useLoader(GLTFLoader, "/scene.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 25.74, -108.97]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group position={[0, -13.81, 56.05]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.material}
            />
          </group>
          <group position={[0, 2.15, -15.52]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.material}
            />
          </group>
          <group position={[0, -10.11, 2.54]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials.material}
            />
          </group>
          <group position={[0, 6.08, 29.68]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group position={[0, 5.01, 29.72]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group position={[0, 27.03, -96.75]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.Object_16.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[53.61, 28.55, -126.99]}
            rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
          >
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[51.68, 23.9, -126.99]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[53.61, 19.24, -126.99]}
            rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI]}
          >
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[58.27, 17.31, -126.99]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
          >
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[62.92, 19.24, -126.99]}
            rotation={[Math.PI / 2, Math.PI / 4, -Math.PI]}
          >
            <mesh
              geometry={nodes.Object_26.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[64.85, 23.9, -126.99]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[62.92, 28.55, -126.99]}
            rotation={[-Math.PI / 2, Math.PI / 4, 0]}
          >
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[58.27, 30.48, -126.99]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[19.56, 46.32, -122.19]}
            rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[18.52, 43.82, -122.19]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[19.56, 41.31, -122.19]}
            rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[22.07, 40.27, -122.19]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[24.58, 41.31, -122.19]}
            rotation={[Math.PI / 2, Math.PI / 4, Math.PI]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[25.61, 43.82, -122.19]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[24.58, 46.32, -122.19]}
            rotation={[-Math.PI / 2, Math.PI / 4, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[22.07, 47.36, -122.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-24.58, 46.32, -122.19]}
            rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_50.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-25.61, 43.82, -122.19]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_52.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-24.58, 41.31, -122.19]}
            rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-22.07, 40.27, -122.19]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_56.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-19.56, 41.31, -122.19]}
            rotation={[Math.PI / 2, Math.PI / 4, Math.PI]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_58.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-18.52, 43.82, -122.19]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_60.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-19.56, 46.32, -122.19]}
            rotation={[-Math.PI / 2, Math.PI / 4, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_62.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-22.07, 47.36, -122.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.54}
          >
            <mesh
              geometry={nodes.Object_64.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-64.85, 23.9, -126.99]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.Object_66.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-62.92, 19.24, -126.99]}
            rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI]}
          >
            <mesh
              geometry={nodes.Object_68.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-58.27, 17.31, -126.99]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
          >
            <mesh
              geometry={nodes.Object_70.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-53.61, 19.24, -126.99]}
            rotation={[Math.PI / 2, Math.PI / 4, -Math.PI]}
          >
            <mesh
              geometry={nodes.Object_72.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-51.68, 23.9, -126.99]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.Object_74.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-53.61, 28.55, -126.99]}
            rotation={[-Math.PI / 2, Math.PI / 4, 0]}
          >
            <mesh
              geometry={nodes.Object_76.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-58.27, 30.48, -126.99]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes.Object_78.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
          <group
            position={[-62.92, 28.55, -126.99]}
            rotation={[-Math.PI / 2, -Math.PI / 4, 0]}
          >
            <mesh
              geometry={nodes.Object_80.geometry}
              material={materials["15_-_Default"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
