import "@styles/globals.css";
import type { AppProps } from "next/app";
import Navbar from "@components/Navbar";
import { useEffect, useState } from "react";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import "@rainbow-me/rainbowkit/styles.css";
import Head from "next/head";
import Footer from "../components/Footer";
import { TronProvider } from "@components/TronProvider";

/* Theming */
const theme = extendTheme({
  styles: {
    global: {
      "*": {
        fontFamily: "Bai Jamjuree",
        color: "white",
      },
      a: {
        _hover: {
          textDecoration: "underline",
        },
      },
      button: {
        backgroundColor: "transparent",
        border: "1px solid gray",
        _hover: {
          border: "1px solid lightgray",
        },
      },
    },
  },
});

function MyApp({ Component, pageProps, router }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <TronProvider>
      <ChakraProvider theme={theme}>
        <Head>
          <title>Nexus: Metaverse Marketplace</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Component {...pageProps} key={router.route} />
        <Footer />
      </ChakraProvider>
    </TronProvider>
  );
}

export default MyApp;
